version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run build!
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./*
  release:
    docker:
      - image: circleci/node:8.9.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      # Create TarGz
      - run: cd ./build && tar -zcf ../build.tar.gz . && cd ../
      # Publish to github
      - run: wget https://github.com/tcnksm/ghr/releases/download/v0.5.2/ghr_v0.5.2_linux_amd64.zip && unzip ghr_v0.5.2_linux_amd64.zip
      - run: ./ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME $VERSION ./build.tar.gz
workflows:
  version: 2
  my_workflow:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
